### ISSUE TITLE
Flags for special use cases

### ISSUE THREAD

**Issue by 5ebastianMeier** [heikomat/minstall#19]
I would like to use flags for two special use cases I currently have:

* debug
   * to get full debug logs of npm actions happening in the background
* no link
   * to be able to run minstall without linking local modules (just a more or less regular installation)

**Comment by heikomat** [comment]
These flags schould be easy to implement. They shoudl be implemented by this evening or by tomorrow

**Comment by heikomat** [comment]
@5ebastianMeier I just uploaded minstall `1.6.0-pre`. It now hast the flags `--no-link`, to tell minstall not to link the local modules to the root-node_modules, and `--loglevel <loglevel>` to set the loglevel. Logs are also greatly improved now, if the loglevel is set.

Please test this for functionality, and test if there aren't any new bugs.

**Comment by heikomat** [comment]
Because these are new features, that shouldn't affect the current default behaviour in any way, i decided to finalize this release, so `1.6.0` is now published
