### ISSUE TITLE
fs-extra was updated to 2.1.0 -> breaks minstall on node 4

### ISSUE THREAD

**Issue by heikomat** [heikomat/minstall#21]
Either check what goes wrong and fix it, or pin fs-extra to 2.0.0

This seems to only happen on node 4, not on node 6 or newer

Minstall is not the only thing that breaks in fs-extra 2.1.0: https://github.com/jprichardson/node-fs-extra/issues/390

**Comment by RyanZim** [comment]
This should be fixed in fs-extra v2.1.1. Sorry about this.

**Comment by moellenbeck** [comment]
+1

**Comment by heikomat** [comment]
@RyanZim
Thanks for taking the time to personally notify us about the fix :)

I have to test this, but i close this issue now, and will only reopen it, if something doesn't work
