### ISSUE TITLE
Investigate install-issues with npm 5

### ISSUE THREAD

**Issue by heikomat** [heikomat/minstall#24]
The installation with npm 5 seems to have a couple new issues that need to be addressed. Here are some error-logs:
```
error: ERROR RUNNING COMMAND npm install --loglevel error imperfect@"^1.0.0" loggerhythm@"^1.0.1" > /dev/null Error: Command failed: npm install --loglevel error imperfect@"^1.0.0" loggerhythm@"^1.0.1" > /dev/null
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/heiko/.npm/_logs/2017-06-02T11_21_20_422Z-debug.log

    at ChildProcess.exithandler (child_process.js:252:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:546:12)

installing module 16/17 -> user

A command from within minstall produced a warning or an error:
command: npm install --loglevel error bcrypt@"^1.0.2" > /dev/null
log-output:


message:
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@8.0.0 (node-v57 ABI) (falling back to source compile with node-gyp)

installing module 17/17 -> voucher error: ERROR RUNNING COMMAND cd /Users/heiko/Desktop/Projekte/leada/admin-app-server/modules/voucher; minstall --isChildProcess Error: Command failed: cd /Users/heiko/Desktop/Projekte/leada/admin-app-server/modules/voucher; minstall --isChildProcess
/bin/sh: minstall: command not found

    at ChildProcess.exithandler (child_process.js:252:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
Unhandled rejection Error: Command failed: cd /Users/heiko/Desktop/Projekte/leada/admin-app-server/modules/voucher; minstall --isChildProcess
/bin/sh: minstall: command not found

    at ChildProcess.exithandler (child_process.js:252:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
```

**Comment by heikomat** [comment]
The issue seems to be with npm5, not minstall: https://github.com/npm/npm/issues/17056.
I'll revisit this issue, as soon as the npm-issue is fixed

**Comment by heikomat** [comment]
it seems, that npm sometimes automatically prunes packages. this could be a problem: https://github.com/npm/npm/issues/16839

EDIT:
yep, it definitely does kill packages: https://github.com/npm/npm/issues/16794

EDIT2:
Also see the current npm5 issue-tracker-issue: https://github.com/npm/npm/issues/16991

**Comment by heikomat** [comment]
This seems to currently be one of the most active npm-issues regarding this topic: https://github.com/npm/npm/issues/16853

**Comment by moellenbeck** [comment]
Can the cmd-option ˋ—no-auto-pruneˋ be a workaround?

**Comment by heikomat** [comment]
@moellenbeck `--no-auto-prune` would probably be a usable workaround, but this option doesn't exist, at least in the regular npm. The `--no-auto-prune`-option referred to in the issue [here](https://github.com/npm/npm/issues/16853#issuecomment-338450203) is something someone added on a fork of npm.

The changes for that option contain only 10 lines of code, and @substack opened a PR on the main npm-repo 5 days ago (https://github.com/npm/npm/pull/18921) but this PR is neither merged, nor its content published in the official npm yet

**Comment by heikomat** [comment]
After getting reports, that minstall 1.3.6 supposedly works with npm5, i can confirm that minstall 1.3.6 does definitely not work with npm5. IF it happened to have worked for you, then that is pure luck, but i have projects that do not work with npm5, even with minstall 1.3.6

I can however confirm, that minstall can be easily upgraded to work with npm5, should this PR get merged: https://github.com/npm/npm/pull/18921

**Comment by cmg-dev** [comment]
@heikomat I consider this as done.

Do you agree?

**Comment by heikomat** [comment]
@cmg-dev if you're talking about investigating only, not about fixing, then yes, this is done. Fixing can be done in #27

**Comment by cmg-dev** [comment]
@heikomat As the issue states "Investigate (...)" I'm confident, we did this extensively.
