### ISSUE TITLE
Alias modules

### ISSUE THREAD

**Issue by 5ebastianMeier** [heikomat/minstall#34]
I'm having a case where I would like to have the ability to treat a scoped npm package as if it was the unscoped version of the same package.

I'm working on `meta-loop` and have a forked version of it that is called `@essential-projects/meta-loop`.

Unfortunately there are many other plugins to the `meta` module that have dependencies on `meta-loop` and I would need to fork a whole lot of packages just to update their dependencies to my scoped package version.

I realize this could be achieved by having a local version of the fork without the scope, but that would not allow me to publish my changes in a friendly way to give others the ability to test my changes without having a local setup with `npm link` like I do.

**Comment by heikomat** [comment]
As it turned out, aliasing the module wasn't helping, because this wouldn't change the dependency-lists of sub-dependencies, so this idea was scrapped
