### ISSUE TITLE
Cannot find minstall as postinstall if install like npm install <some-package-name>

### ISSUE THREAD

**Issue by moellenbeck** [heikomat/minstall#8]
If you try to install a package that depend on minstall via `npm install package-name`, the postinstall cannot be found.

**Comment by moellenbeck** [comment]
Current workaround in cwd:
- npm install minstall

**Comment by heikomat** [comment]
@moellenbeck It seems, that you have put `minstall` in the `devDependencies`, not in the `dependencies`, thus minstall wasn't avaliable on installation. If this fixes your problem, pease close this issue

**Comment by heikomat** [comment]
I could recreate the problem and can confirm, that putting uninstall in the dependencies, instead of devDependencies fixes the issue
