### ISSUE TITLE
Want to open a package.json in current working directory that didn't exist

### ISSUE THREAD

**Issue by moellenbeck** [heikomat/minstall#9]
If install via `npm install <package-name>`minstall want to open a package.json in the current working directory, but it didn't exist.

**Comment by moellenbeck** [comment]
Current workaround:
- add a empty package.jon
- npm init

**Comment by heikomat** [comment]
@moellenbeck It seems, that you have put `minstall` in the `devDependencies`, not in the `dependencies`, thus minstall wasn't avaliable on installation. If this fixes your problem, pease close this issue

**Comment by heikomat** [comment]
I can not recreate the problem. Could you please provide me with a specific scenario, where this happens? @moellenbeck

**Comment by moellenbeck** [comment]
After update to minstall 1.3.1 the bug did'nt exist anymore
